apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-chart.fullname" . }}-config
  labels:
    {{- include "gateway-chart.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Jwt": {
        "Issuer": "{{ .Values.config.jwt.issuer }}",
        "Audience": "{{ .Values.config.jwt.audience }}",
        "Key": "{{ .Values.config.jwt.key }}"
      },
      "Serilog": {
        "Using": ["Serilog.Sinks.Console"],
        "MinimumLevel": "Information",
        "WriteTo": [
          { "Name": "Console" }
        ]
      },
      "ReverseProxy": {
        "Routes": {
          "notification-route": {
            "ClusterId": "notification-cluster",
            "Match": {
              "Path": "/api/notifications/{**catch-all}"
            },
            "Transforms": [
              { "PathPattern": "/api/notifications/{**catch-all}" }
            ]
          },
          "notification-route-hub": {
            "ClusterId": "notification-cluster",
            "Match": {
              "Path": "/hub/notifyHub/{**catch-all}"
            },
            "Transforms": [
              { "PathPattern": "/hub/notifyHub/{**catch-all}" }
            ]
          },
          "todo-route": {
            "ClusterId": "todo-cluster",
            "Match": {
              "Path": "/api/Todos/{**catch-all}"
            },
            "Transforms": [
              { "PathPattern": "/api/Todos/{**catch-all}" }
            ]
          }
        },
        "Clusters": {
          "notification-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://notification-service:80/"
              }
            }
          },
          "todo-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://todo-service:80/"
              }
            }
          }
        }
      }
    }